### PR TITLE
fix(modal): improve modal components

### LINKED ISSUE #586: Modal Dialog Form: UX improvements relating to closing of component
## 🚀 Feature Proposal

When in a Modal Dialog Form with unsaved changes:

1. When the user wants to close the modal dialog (either via the x button, the close button or when they click outside of the modal):
     - Prompt user with a confirmation message e.g. "Are you sure you want to exit without saving changes?".
     - If the user chooses _Yes_, then close the modal form, if they choose _No_, do not close the modal.

2. Prevent the clicking outside of the Modal window from closing the Modal.

## Motivation

- If/when a user fills in data in a Modal Form, and accidentally click outside the Modal, the form will be closed and any unsaved change lost. This could lead to user frustration and is not a really good user experience.

- Also, in general, if/when a user wants to close a form with unsaved changes, it is a maybe good idea to prompt if they are sure they want to exit without saving changes.

## Example

When adding data via Modal forms such as adding a Care Plan or Care Goal, with so many fields, we don't want users to lose their unsaved changes if they should accidentally close the modal form.

### PR DESCRIPTION
**Pull request by michaelkramer**
Fixes #586 .

**Changes proposed in this pull request:**

* Include a backdrop component. Specify 'static' for a backdrop that doesn't trigger an "onHide" when clicked. Default = true
   **backdrop?: true | false | 'static'**
  
* Callback fired before the Modal transitions in
  **onEnter?(node: HTMLElement): any**

* Callback fired after the Modal finishes transitioning in
  **onEntered?(node: HTMLElement): any**

* Callback fired as the Modal begins to transition in
   **onEntering?(node: HTMLElement): any**
  
* Callback fired right before the Modal transitions out
  **onExit?(node: HTMLElement): any**
  
* Callback fired after the Modal finishes transitioning out
  **onExited?(node: HTMLElement): any**

* Callback fired as the Modal begins to transition out
  **onExiting?(node: HTMLElement): any**

The modal will not close when you click outside the modal.
```
backdrop={"static"}
```

Full Example
```
<Modal
          show={show}
          toggle={() => setShow(!show)}
          title="This is a modal title!"
backdrop={"static"}
          body={
            <div>
              <p>And this is a modal body.</p>
              <div>
                Simple example with just one button. <br /> The modal body can be any JSX.
              </div>
            </div>
          }
          closeButton={{
            children: 'Close me',
            onClick: () => {
              console.log('clicked close')
              setShow(!show)
            },
          }}
        />
```

### CODE REVIEW

**Comment by blestab** [comment]
Thanks @michaelkramer 

This should resolve requirement  number 2, _"Prevent the clicking outside of the Modal window from closing the Modal."_. I don't see us addressing requirement number 1, does this mean that this responsibility is passed onto the component where the modal is used?

**Comment by michaelkramer** [comment]
Yes, I would think the "Confirm Close alert" would need more customization.  Like because of different language.

File: src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -49,6 +49,7 @@ interface Props {
    * Styilng through inline CSSProperties
    */
   style?: CSSProperties
+  [x: string]: any
```
Comment (jackcmeyer) [inline src/components/Modal/Modal.tsx:52]: I don't think that having this component accept any prop is a good idea for the following reasons: 

1. It creates an undefined interface which leads to developer confusion
2. It does not allow the component to be documented
3. In this case, it leaks the implementation details since we are using it to essentially expose the props of the underlying modal implementation. Making sure that the modal implementation could be changed without breaking the public interface is important for this library.

We should refactor this to expose the props that we want to use for customization with proper names for the HospitalRun context.

**Review by jackcmeyer — CHANGES_REQUESTED** [review]

File: src/components/Modal/Modal.tsx (hunk 1 above)
Comment (michaelkramer) [reply src/components/Modal/Modal.tsx:52]: I will gladly change for better documentations, but I'm wondering why we would need to if the `hospitalRun/components` is just a wrapper for `react-bootstrap` which has good documentation?

Now I understand if at some point another new better `component library` comes around that then you would like to change to.  Having everything just passed down will require a TON! of refactoring on the actual site vs just in the component.

Well I just convinced myself into not allowing the props to be passed down.  I'll correct this request.

**Comment by michaelkramer** [comment]
I have changed the props to include:
1. backdrop
2. onEnter
3. onEntering
4. onEntered
5. onExit
6. onExiting
7. onExited

I still feel like the confirmation modal/popup should be done outside the component.  Which can be done with 
```
backdrop={'static'}
```
the `onEvents` are there because someone might need them in the future.

**Review by jackcmeyer — APPROVED** [review]
