### PR TITLE
fix(panel): make panel collapse on header click

### LINKED ISSUE #229: Make collapsible panel collapse when clicking on the header
## 🚀 Feature Proposal

Right now, to make the Collapsible Panel collapse you must click the carrot. It would be a nice user experience to also allow the header to be clicked on to make it collapse.  

## Motivation

Easier user experience.

## Related Issues
#138

### PR DESCRIPTION
**Pull request by ocBruno**
fix #229

**Changes proposed in this pull request:**
- Add onClick anonymous function to Card.Header that opens/closes the Panel 
- Add necessary complementary test

### CODE REVIEW

File: src/components/Panel/Panel.tsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ const Panel = (props: Props) => {
   return (
     <Card border={color}>
       {title && (
-        <Card.Header style={{ textAlign: 'left' }}>
+        <Card.Header onClick={() => setOpen(!open)} style={{ textAlign: 'left' }}>
```
Comment (jackcmeyer) [inline src/components/Panel/Panel.tsx]: I noticed if the panel is not collapsible, then the onclick event still fires causing the panel to collapse. 

If the panel is not collapsible, then it should should not collapse when clicking the header.

Comment (ocBruno) [reply src/components/Panel/Panel.tsx]: Added a complementary test and a conditional to ensure the panel is collapsible before toggling the collapse.
I am still new to testing and looking to practice. I'm not too sure exactly too what extent we should test these components. Should I also create a test to make sure clicking on the toggle icon collapses and opens the panel? I hadn't seen one present so I wasn't sure but if there are any missing tests or mistakes send me a reply!

File: src/components/Panel/Panel.tsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ const Panel = (props: Props) => {
   return (
     <Card border={color}>
       {title && (
-        <Card.Header style={{ textAlign: 'left' }}>
+        <Card.Header onClick={() => collapsible && setOpen(!open)} style={{ textAlign: 'left' }}>
```
Comment (jackcmeyer) [inline src/components/Panel/Panel.tsx]: When the header is collapsible can we add the pointer cursor to the header?

File: test/panel.test.tsx [hunk 3]
```diff
@@ -55,7 +55,33 @@ describe('Panel', () => {
     expect(panelWrapper.find(Icon)).toHaveLength(1)
     expect(bodyWrapper.find(Icon)).toHaveLength(1)
   })
+  it('Panel collapse on header click', () => {
```
Comment (jackcmeyer) [inline test/panel.test.tsx]: per the convention of the tests, could we rename the test to: 

`it('should collapse the panel on header click')`

File: test/panel.test.tsx [hunk 4]
```diff
@@ -55,7 +55,33 @@ describe('Panel', () => {
...
+        <p>You can open and close me!</p>
+      </Panel>,
+    )
 
+    const cardHeaderWrapper = panelWrapper.find(Card.Header).first()
+    expect(panelWrapper.find('.collapse.show')).toHaveLength(1)
+    cardHeaderWrapper.simulate('click')
+    expect(panelWrapper.find('.collapsing')).toHaveLength(1)
+  })
+  it('Panel open on header click', () => {
```
Comment (jackcmeyer) [inline test/panel.test.tsx]: See above comment about test name convention

**Comment by ocBruno** [comment]
> We should have some tests to show that the panel header cannot be clicked when the panel is not collapsible.

Hey @jackcmeyer, thanks for the spotting me on the test convention mistakes!
I wasn't sure if I was supposed to refactor other tests I hadn't modified but if anything tell me which should remain the same. 

I thought applying the 'should' convention to everything could improve the design but I'm not sure what others think. Also wondering if we should remove text selection on panel headers or not if anyone wants to chime in.

File: src/components/Panel/Panel.tsx (hunk 1 above)
Comment (jackcmeyer) [reply src/components/Panel/Panel.tsx]: In general, if it can be tested, we should probably test it. 

it sounds like a test to check that clicking on the icon collapses and opens the panel seems like a good test!

File: src/components/Panel/Panel.tsx [hunk 5]
```diff
@@ -34,9 +36,12 @@ const Panel = (props: Props) => {
   )
 
   return (
-    <Card border={color}>
+    <Card className={className ? className.concat('', '') : className} border={color}>
```
Comment (jackcmeyer) [inline src/components/Panel/Panel.tsx]: We should be able to just pass `className` to this prop so it could simply be `className={className}`. If `className` prop is undefined it wont' have any impact.

**Comment by fox1t** [comment]
Nice @ocBruno! Thanks for your contribution!

**Comment by ocBruno** [comment]
> Nice @ocBruno! Thanks for your contribution!

Here to help! Any design/ux or frontend priorities send me a message!
